### ISSUE TITLE
Missing prerequisites

### ISSUE THREAD

**Issue by sskorol** [Myzhar/ldrobot-lidar-ros2#3]
Hi @Myzhar,

I want to use this code with LD06 lidar. Tried to follow the instructions from README but had initially failed to locate ZED (googled it and installed the latest ZED SDK). Now I'm failing to locate `zed_interfaces`:

```shell
Starting >>> zed_components
--- stderr: zed_components                         
CMake Warning at CMakeLists.txt:69 (find_package):
  By not providing "Findzed_interfaces.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "zed_interfaces", but CMake did not find one.

  Could not find a package configuration file provided by "zed_interfaces"
  with any of the following names:

    zed_interfacesConfig.cmake
    zed_interfaces-config.cmake

  Add the installation prefix of "zed_interfaces" to CMAKE_PREFIX_PATH or set
  "zed_interfaces_DIR" to a directory containing one of the above files.  If
  "zed_interfaces" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error at /opt/ros/foxy/share/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake:77 (message):
  ament_target_dependencies() the passed package name 'zed_interfaces' was
  not found before
Call Stack (most recent call first):
  CMakeLists.txt:143 (ament_target_dependencies)
```

I'm a bit confused here. Could you please elaborate, why do we need ZED to control LiDAR? And if it's a must-have framework / set of libs, what else I'm missing here? As there are no requirements in README that mention ZED.

P.S. I'm on Ubuntu 20, ROS2 foxy. And failure occurs on the following step:
```shell
colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release
```

Thanks,
Sergey

**Comment by Myzhar** [comment]
@sskorol sorry, my fault.
I copied and paste the instructions from another repository that I made and I forgot to change the link 😅
I fixed the README. Do not forget to delete the folder that you created in your workspace to remove the wrong repository that you cloned.

**Comment by sskorol** [comment]
@Myzhar yeap, I've already noticed the wrong link. Took me a while to figure that out though, as I usually just copy-paste git clone command from the instruction. :) Anyway, thanks for updating the README. It works.

**Comment by sskorol** [comment]
@Myzhar BTW, tried to set it up on RPi 3 model A+. There was a missing udev library in the system. So I additionally installed `libidev-dev` via apt.

**Comment by Myzhar** [comment]
I add it to the requirements. Thx
