### ISSUE TITLE
SLAM integration

### ISSUE THREAD

**Issue by sskorol** [Myzhar/ldrobot-lidar-ros2#4]
Hi @Myzhar,

Just curious if it's possible to integrate this node with [hector_slam](https://github.com/tu-darmstadt-ros-pkg/hector_slam)? They are still on ROS1 (and I'm not really sure if they'd migrate in the nearest future). I guess there's a difference between topics/frames used by `ldlidar` for publishing and what `hector_slam` expects while subscribing. Do you have any thoughts regarding the common steps required for such integration? Note that it seems like `hector_slam` can work w/o odometry, just by using lidar data.

Thanks,
Sergey

**Comment by Myzhar** [comment]
There is a `ros1_bridge` package that allows ROS1 and ROS2 to coexist and communicate:
https://index.ros.org/p/ros1_bridge/
Sincerely I never used hector_slam, so I do not know the topics that it requires, but topic name remapping is always a good solution in similar cases:
https://wiki.ros.org/roslaunch/XML/remap

Regarding the frame name, there is a parameter that allows you to change it according to your requirements:
https://github.com/Myzhar/ldrobot-lidar-ros2/blob/main/ldlidar_node/config/ldlidar.yaml#L15
